# pull official base image
FROM node:16.20.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts -g --silent

# add app
COPY . ./

# change ownership
RUN chown -R node:node /app
RUN chown -R node:node /.npm

# start app
CMD ["npm", "start"]
