apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ams-pp
  namespace: demo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: quay.io/zroubalik/ams-app:dev
          imagePullPolicy: Always
          env:
            - name: BROKER_URI
              value: http://broker-ingress.knative-eventing.svc.cluster.local/demo/default
          ports:
            - containerPort: 3000
