---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: demo
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: ams-data-app-sink-binding
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    name: ams-data-app-deployment
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default