---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-distance
  namespace: demo
spec:
  broker: default
  filter:
    attributes:
      type: scooters.list
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: distance