FROM node:14-alpine

RUN apk add --no-cache curl &&\
    mkdir -p /home/node/app &&\
    chown -R node:node /home/node/app

WORKDIR /home/node/app

RUN chgrp -R 0 /home/node/app &&\
    chmod -R g=u /home/node/app

COPY frontend/package*.json /home/node/app/
USER 1000
RUN npm install

COPY --chown=node:node frontend /home/node/app
RUN chmod 666 /home/node/app/node_modules/.cache/.eslintcache

EXPOSE 3000
CMD ["npm", "start"]
