FROM registry.access.redhat.com/ubi8/nodejs-14

WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY backend .

EXPOSE 3333

# Start the application
CMD ["npm", "start"]
